/* ============================================================================
   AUTO-GENERATED — DO NOT EDIT BY HAND.

   Generated by scripts/sync-live-fixtures.mjs from src/live/fixtures/*.json,
   the same Phase 1 fixture files the frontend imports directly. Regenerate
   with:

     npm run sync:fixtures

   supabase/functions/live-data/tests/fixtureDrift.test.ts fails if this file
   no longer matches the source JSON, so a forgotten regeneration is caught
   by the test suite rather than silently shipped.
   ========================================================================== */

export const O_COMPANY = {
  "ticker": "O",
  "cik": "0000726728",
  "name": "Realty Income Corporation",
  "companyType": "equity-reit",
  "exchange": "NYSE",
  "description": "Net-lease equity REIT that owns and leases free-standing commercial properties across the U.S. and parts of Europe under long-term contracts; pays shareholders a monthly dividend.",
  "provenance": {
    "source": "Realty Income Corporation — Q2 2026 Earnings Release & Supplemental Information",
    "sourceType": "company-supplemental",
    "documentType": "supplemental",
    "documentUrl": "https://www.realtyincome.com/sites/realty-income/files/2026-08/realty-income-earnings-release-and-supplemental-information-q2-2026.pdf",
    "filingReferenceUrl": "https://www.sec.gov/Archives/edgar/data/0000726728/000072672826000044/o-991q22026.htm"
  },
  "retrievedAt": "2026-08-11"
} as const;

export const O_FACTS = [
  {
    "ticker": "O",
    "metricKey": "reportedAffoPerShare",
    "value": 1.09,
    "unavailableReason": null,
    "currency": "USD",
    "unit": "USD_per_share",
    "classification": "reported",
    "period": {
      "fiscalYear": 2026,
      "fiscalQuarter": 2,
      "periodType": "quarterly",
      "periodStart": "2026-04-01",
      "periodEnd": "2026-06-30"
    },
    "asOf": "2026-06-30",
    "retrievedAt": "2026-08-11",
    "freshness": "SNAPSHOT",
    "provenance": {
      "source": "Realty Income Corporation — Q2 2026 Earnings Release & Supplemental Information",
      "sourceType": "company-supplemental",
      "documentType": "supplemental",
      "documentUrl": "https://www.realtyincome.com/sites/realty-income/files/2026-08/realty-income-earnings-release-and-supplemental-information-q2-2026.pdf",
      "filingReferenceUrl": "https://www.sec.gov/Archives/edgar/data/0000726728/000072672826000044/o-991q22026.htm",
      "companyDefinitionNote": "Realty Income's own AFFO measure (non-GAAP): starts from net income available to common stockholders, adds back real estate depreciation/amortization and impairments, removes gains on property sales, and adjusts for other items the company treats as non-comparable to ongoing operations. Confirmed directly in the release's diluted-AFFO reconciliation table for the three months ended June 30, 2026."
    }
  },
  {
    "ticker": "O",
    "metricKey": "reportedDividendPerShare",
    "value": 0.8115,
    "unavailableReason": null,
    "currency": "USD",
    "unit": "USD_per_share",
    "classification": "reported",
    "period": {
      "fiscalYear": 2026,
      "fiscalQuarter": 2,
      "periodType": "quarterly",
      "periodStart": "2026-04-01",
      "periodEnd": "2026-06-30"
    },
    "asOf": "2026-06-30",
    "retrievedAt": "2026-08-11",
    "freshness": "SNAPSHOT",
    "provenance": {
      "source": "Realty Income Corporation — Q2 2026 Earnings Release & Supplemental Information",
      "sourceType": "company-supplemental",
      "documentType": "supplemental",
      "documentUrl": "https://www.realtyincome.com/sites/realty-income/files/2026-08/realty-income-earnings-release-and-supplemental-information-q2-2026.pdf",
      "filingReferenceUrl": "https://www.sec.gov/Archives/edgar/data/0000726728/000072672826000044/o-991q22026.htm",
      "companyDefinitionNote": "Confirmed directly in the release's financial data table (cash dividends paid per common share) for the three months ended June 30, 2026. The release's narrative text separately rounds this same figure to $0.812."
    }
  },
  {
    "ticker": "O",
    "metricKey": "reportedAffoPayoutRatio",
    "value": 74.5,
    "unavailableReason": null,
    "currency": "",
    "unit": "percent",
    "classification": "reported",
    "period": {
      "fiscalYear": 2026,
      "fiscalQuarter": 2,
      "periodType": "quarterly",
      "periodStart": "2026-04-01",
      "periodEnd": "2026-06-30"
    },
    "asOf": "2026-06-30",
    "retrievedAt": "2026-08-11",
    "freshness": "SNAPSHOT",
    "provenance": {
      "source": "Realty Income Corporation — Q2 2026 Earnings Release & Supplemental Information",
      "sourceType": "company-supplemental",
      "documentType": "supplemental",
      "documentUrl": "https://www.realtyincome.com/sites/realty-income/files/2026-08/realty-income-earnings-release-and-supplemental-information-q2-2026.pdf",
      "filingReferenceUrl": "https://www.sec.gov/Archives/edgar/data/0000726728/000072672826000044/o-991q22026.htm",
      "companyDefinitionNote": "The company's own stated payout ratio, given directly in the release: monthly dividends represented 74.5% of diluted AFFO per share of $1.09 for the quarter. This is Realty Income's own figure, computed from unrounded internal dollars — it is not a COLD calculation."
    }
  },
  {
    "ticker": "O",
    "metricKey": "occupancy",
    "value": 98.8,
    "unavailableReason": null,
    "currency": "",
    "unit": "percent",
    "classification": "reported",
    "period": {
      "fiscalYear": 2026,
      "fiscalQuarter": 2,
      "periodType": "quarterly",
      "periodStart": "2026-04-01",
      "periodEnd": "2026-06-30"
    },
    "asOf": "2026-06-30",
    "retrievedAt": "2026-08-11",
    "freshness": "SNAPSHOT",
    "provenance": {
      "source": "Realty Income Corporation — Q2 2026 Earnings Release & Supplemental Information",
      "sourceType": "company-supplemental",
      "documentType": "supplemental",
      "documentUrl": "https://www.realtyincome.com/sites/realty-income/files/2026-08/realty-income-earnings-release-and-supplemental-information-q2-2026.pdf",
      "filingReferenceUrl": "https://www.sec.gov/Archives/edgar/data/0000726728/000072672826000044/o-991q22026.htm",
      "companyDefinitionNote": "Confirmed directly in the release: portfolio occupancy as of June 30, 2026, stated in the same sentence as the March 31, 2026 and June 30, 2025 comparatives."
    }
  },
  {
    "ticker": "O",
    "metricKey": "occupancy",
    "value": 98.6,
    "unavailableReason": null,
    "currency": "",
    "unit": "percent",
    "classification": "reported",
    "period": {
      "fiscalYear": 2025,
      "fiscalQuarter": 2,
      "periodType": "quarterly",
      "periodStart": "2025-04-01",
      "periodEnd": "2025-06-30"
    },
    "asOf": "2025-06-30",
    "retrievedAt": "2026-08-11",
    "freshness": "SNAPSHOT",
    "provenance": {
      "source": "Realty Income Corporation — Q2 2026 Earnings Release & Supplemental Information (prior-year comparative)",
      "sourceType": "company-supplemental",
      "documentType": "supplemental",
      "documentUrl": "https://www.realtyincome.com/sites/realty-income/files/2026-08/realty-income-earnings-release-and-supplemental-information-q2-2026.pdf",
      "filingReferenceUrl": "https://www.sec.gov/Archives/edgar/data/0000726728/000072672826000044/o-991q22026.htm",
      "companyDefinitionNote": "Confirmed directly in the same sentence of the release that states the current-period occupancy figure."
    }
  },
  {
    "ticker": "O",
    "metricKey": "propertyCount",
    "value": 15588,
    "unavailableReason": null,
    "currency": "",
    "unit": "count",
    "classification": "reported",
    "period": {
      "fiscalYear": 2026,
      "fiscalQuarter": 2,
      "periodType": "quarterly",
      "periodStart": "2026-04-01",
      "periodEnd": "2026-06-30"
    },
    "asOf": "2026-06-30",
    "retrievedAt": "2026-08-11",
    "freshness": "SNAPSHOT",
    "provenance": {
      "source": "Realty Income Corporation — Q2 2026 Earnings Release & Supplemental Information",
      "sourceType": "company-supplemental",
      "documentType": "supplemental",
      "documentUrl": "https://www.realtyincome.com/sites/realty-income/files/2026-08/realty-income-earnings-release-and-supplemental-information-q2-2026.pdf",
      "filingReferenceUrl": "https://www.sec.gov/Archives/edgar/data/0000726728/000072672826000044/o-991q22026.htm",
      "companyDefinitionNote": "Confirmed directly in the release: total properties owned or held interests in as of June 30, 2026."
    }
  }
] as const;

export const O_QUOTE = {
  "ticker": "O",
  "price": null,
  "previousClose": null,
  "changePct": null,
  "currency": "USD",
  "unit": "USD_per_share",
  "marketState": null,
  "asOf": null,
  "unavailableReason": "provider_not_connected",
  "freshness": "UNAVAILABLE",
  "provenance": {
    "source": "No market-data provider is connected in Phase 1",
    "sourceType": "market-data-provider",
    "documentType": null,
    "documentUrl": null
  }
} as const;

export const BRKB_COMPANY = {
  "ticker": "BRK.B",
  "cik": "0001067983",
  "name": "Berkshire Hathaway Inc.",
  "companyType": "diversified-holding-company",
  "exchange": "NYSE",
  "description": "Diversified holding company with insurance and reinsurance, freight rail (BNSF), utilities and energy, and manufacturing, service and retail operations.",
  "provenance": {
    "source": "Berkshire Hathaway Inc. — Second Quarter 2026 News Release",
    "sourceType": "company-supplemental",
    "documentType": "press-release",
    "documentUrl": "https://www.berkshirehathaway.com/news/aug0826.pdf"
  },
  "retrievedAt": "2026-08-11"
} as const;

export const BRKB_FACTS = [
  {
    "ticker": "BRK.B",
    "metricKey": "operatingEarnings",
    "value": 12983,
    "unavailableReason": null,
    "currency": "USD",
    "unit": "USD_millions",
    "classification": "reported",
    "period": {
      "fiscalYear": 2026,
      "fiscalQuarter": 2,
      "periodType": "quarterly",
      "periodStart": "2026-04-01",
      "periodEnd": "2026-06-30"
    },
    "asOf": "2026-06-30",
    "retrievedAt": "2026-08-11",
    "freshness": "SNAPSHOT",
    "provenance": {
      "source": "Berkshire Hathaway Inc. — Second Quarter 2026 News Release",
      "sourceType": "company-supplemental",
      "documentType": "press-release",
      "documentUrl": "https://www.berkshirehathaway.com/news/aug0826.pdf",
      "companyDefinitionNote": "Berkshire's own non-GAAP measure: net earnings excluding investment gains/losses and certain impairments of goodwill, intangible assets and equity-method investments."
    }
  },
  {
    "ticker": "BRK.B",
    "metricKey": "netEarningsPerClassBShare",
    "value": 11.91,
    "unavailableReason": null,
    "currency": "USD",
    "unit": "USD_per_share",
    "classification": "reported",
    "period": {
      "fiscalYear": 2026,
      "fiscalQuarter": 2,
      "periodType": "quarterly",
      "periodStart": "2026-04-01",
      "periodEnd": "2026-06-30"
    },
    "asOf": "2026-06-30",
    "retrievedAt": "2026-08-11",
    "freshness": "SNAPSHOT",
    "provenance": {
      "source": "Berkshire Hathaway Inc. — Second Quarter 2026 News Release",
      "sourceType": "company-supplemental",
      "documentType": "press-release",
      "documentUrl": "https://www.berkshirehathaway.com/news/aug0826.pdf",
      "companyDefinitionNote": "GAAP net earnings attributable to Berkshire shareholders, per average equivalent Class B share (1/1,500th of the Class A figure)."
    }
  },
  {
    "ticker": "BRK.B",
    "metricKey": "netEarningsPerClassBShare",
    "value": 5.73,
    "unavailableReason": null,
    "currency": "USD",
    "unit": "USD_per_share",
    "classification": "reported",
    "period": {
      "fiscalYear": 2025,
      "fiscalQuarter": 2,
      "periodType": "quarterly",
      "periodStart": "2025-04-01",
      "periodEnd": "2025-06-30"
    },
    "asOf": "2025-06-30",
    "retrievedAt": "2026-08-11",
    "freshness": "SNAPSHOT",
    "provenance": {
      "source": "Berkshire Hathaway Inc. — Second Quarter 2026 News Release (prior-year comparative)",
      "sourceType": "company-supplemental",
      "documentType": "press-release",
      "documentUrl": "https://www.berkshirehathaway.com/news/aug0826.pdf"
    }
  },
  {
    "ticker": "BRK.B",
    "metricKey": "insuranceFloat",
    "value": 177.5,
    "unavailableReason": null,
    "currency": "USD",
    "unit": "USD_billions",
    "classification": "reported",
    "period": {
      "fiscalYear": 2026,
      "fiscalQuarter": 2,
      "periodType": "quarterly",
      "periodStart": "2026-04-01",
      "periodEnd": "2026-06-30"
    },
    "asOf": "2026-06-30",
    "retrievedAt": "2026-08-11",
    "freshness": "SNAPSHOT",
    "provenance": {
      "source": "Berkshire Hathaway Inc. — Second Quarter 2026 News Release",
      "sourceType": "company-supplemental",
      "documentType": "press-release",
      "documentUrl": "https://www.berkshirehathaway.com/news/aug0826.pdf",
      "companyDefinitionNote": "Company's own measure, stated as approximate: net liabilities assumed under insurance and reinsurance contracts, before the cost of holding them."
    }
  }
] as const;

export const BRKB_QUOTE = {
  "ticker": "BRK.B",
  "price": null,
  "previousClose": null,
  "changePct": null,
  "currency": "USD",
  "unit": "USD_per_share",
  "marketState": null,
  "asOf": null,
  "unavailableReason": "provider_not_connected",
  "freshness": "UNAVAILABLE",
  "provenance": {
    "source": "No market-data provider is connected in Phase 1",
    "sourceType": "market-data-provider",
    "documentType": null,
    "documentUrl": null
  }
} as const;
